kind: pipeline
type: docker
name: default

steps:
- name: client-prettier-check
  image: node
  commands:
  - cd client
  - yarn install
  - yarn prettier --check '**/*.js'
- name: server-prettier-check
  image: node
  commands:
  - cd server
  - yarn install
  - yarn prettier --check '**/*.js'
